server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?useSSL=false
    username: root
    password: 510218
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.11.128
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis:
  type-aliases-package: cn.itcast.hotel.pojo
  configuration:
    map-underscore-to-camel-case: true
